web:
  restart: always
  build: ./pyweb
  expose:
    - "8007"
  links:
    - db
  volumes:
    - /etc/localtime:/etc/localtime:ro
  command: /usr/local/bin/gunicorn -w 2 -b :8007 server:app

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "8007:80"
  volumes:
    - /etc/localtime:/etc/localtime:ro
  volumes_from:
    - web
  links:
    - web

harvest:
   build: ./pyimage/
   links:
    - db
   volumes:
    - /etc/localtime:/etc/localtime:ro
    - .:/code

db:
   image: mongo:latest
   volumes:
     - /etc/localtime:/etc/localtime:ro
     - './save/:/save'
     - './data:/data/db'

